# Build étape
FROM node:20-alpine AS build

WORKDIR /app

COPY package*.json ./
RUN npm install

# Installer vite globalement pour éviter le problème de permission
RUN npm install -g vite

COPY . .
RUN npm run build
