const EventType ={
  CLIENT_ADDED: "CLIENT_ADDED",
  CLIENT_UPDATED: "CLIENT_UPDATED",
  CLIENT_DELETED: "CLIENT_DELETED",

  OFFRE_ADDED: "OFFRE_ADDED",
  OFFRE_UPDATED: "OFFRE_UPDATED",
  OFFRE_DELETED: "OFFRE_DELETED",

  RESERVATION_ADDED: "RESERVATION_ADDED",
  RESERVATION_UPDATED: "RESERVATION_UPDATED",
  RESERVATION_DELETED: "RESERVATION_DELETED",

  IMAGE_ADDED: "IMAGE_ADDED",
  IMAGE_UPDATED: "IMAGE_UPDATED",
  IMAGE_DELETED: "IMAGE_DELETED"
  ,NOTIFICATION_ADD: "NOTIFICATION_ADD",
  NOTIFICATION_UPDATED: "NOTIFICATION_UPDATED",
  NOTIFICATION_DELETED: "NOTIFICATION_DELETED"
}


module.exports = EventType; 